---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.2-alpine3.15
          env:
            - name: POSTGRES_DB
              value: rootdb
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 5432
              name: postgres
          readinessProbe:
            exec:
              command:
              - pg_isready
              - -h
              - localhost
              - -d
              - rootdb
              - -U
              - root
